import type {
  User,
  Vehicle,
  Shipment,
  Conversation,
  Message,
  Task,
  AppNotification,
} from '@/types';

export const mockUsers: User[] = [
  {
    id: 'u1',
    name: 'Raheel Hayat',
    email: 'raheel@atj.com',
    password: 'demo',
    department: 'Operations',
    role: 'staff',
    roleLabel: 'Operations Executive',
    status: 'online',
    avatarColor: 'bg-emerald-500',
  },
  {
    id: 'u2',
    name: 'Japan Manager',
    email: 'japan@atj.com',
    password: 'demo',
    department: 'Japan Operations',
    role: 'manager',
    roleLabel: 'Manager',
    status: 'online',
    avatarColor: 'bg-sky-500',
  },
  {
    id: 'u3',
    name: 'Sales Team',
    email: 'sales@atj.com',
    password: 'demo',
    department: 'Sales',
    role: 'staff',
    roleLabel: 'Sales Executive',
    status: 'online',
    avatarColor: 'bg-violet-500',
  },
  {
    id: 'u4',
    name: 'Shipping Team',
    email: 'shipping@atj.com',
    password: 'demo',
    department: 'Shipping',
    role: 'staff',
    roleLabel: 'Shipping Executive',
    status: 'away',
    avatarColor: 'bg-amber-500',
  },
  {
    id: 'u5',
    name: 'Management',
    email: 'admin@atj.com',
    password: 'demo',
    department: 'Management',
    role: 'admin',
    roleLabel: 'Administrator',
    status: 'online',
    avatarColor: 'bg-rose-500',
  },
];

export const mockVehicles: Vehicle[] = [
  {
    id: 'v1',
    reference: 'AT21235',
    make: 'Toyota',
    model: 'Hiace',
    chassis: 'TRH200-5003437',
    status: 'BOOKED',
    destination: 'Guyana',
    booking: 'JP5827400',
    year: 2020,
    color: 'White',
    price: 18500,
  },
  {
    id: 'v2',
    reference: 'AT21236',
    make: 'Toyota',
    model: 'Prius',
    chassis: 'ZVW50-1234567',
    status: 'RESERVED',
    destination: 'Jamaica',
    booking: 'JP5827401',
    year: 2019,
    color: 'Silver',
    price: 14200,
  },
  {
    id: 'v3',
    reference: 'AT21237',
    make: 'Toyota',
    model: 'Aqua',
    chassis: 'NHP10-9876543',
    status: 'PARTIAL PAID',
    destination: 'Guyana',
    booking: 'JP5827402',
    year: 2018,
    color: 'Blue',
    price: 9800,
  },
  {
    id: 'v4',
    reference: 'AT21238',
    make: 'Nissan',
    model: 'Caravan',
    chassis: 'VME0-2468135',
    status: 'AVAILABLE',
    destination: 'Bangladesh',
    booking: 'JP5827403',
    year: 2017,
    color: 'White',
    price: 11200,
  },
  {
    id: 'v5',
    reference: 'AT21239',
    make: 'Honda',
    model: 'Fit',
    chassis: 'GK5-3690258',
    status: 'SHIPPED',
    destination: 'Kenya',
    booking: 'JP5827404',
    year: 2016,
    color: 'Red',
    price: 7600,
  },
];

export const mockShipments: Shipment[] = [
  {
    id: 's1',
    container: 'TYOGD5827400',
    destination: 'Guyana',
    etd: '03 September 2026',
    eta: '28 September 2026',
    status: 'SHIPPED',
    vehicleIds: ['v1', 'v2', 'v3'],
  },
  {
    id: 's2',
    container: 'TYOGD5827401',
    destination: 'Jamaica',
    etd: '15 September 2026',
    eta: '10 October 2026',
    status: 'BOOKING',
    vehicleIds: ['v2'],
  },
  {
    id: 's3',
    container: 'TYOGD5827402',
    destination: 'Kenya',
    etd: '20 September 2026',
    eta: '15 October 2026',
    status: 'LOADED',
    vehicleIds: ['v5'],
  },
];

export const mockConversations: Conversation[] = [
  {
    id: 'c-dm-u2',
    type: 'dm',
    name: 'Japan Manager',
    subtitle: 'Japan Operations',
    memberIds: ['u2'],
  },
  {
    id: 'c-dm-u3',
    type: 'dm',
    name: 'Sales Team',
    subtitle: 'Sales',
    memberIds: ['u3'],
  },
  {
    id: 'c-dm-u4',
    type: 'dm',
    name: 'Shipping Team',
    subtitle: 'Shipping',
    memberIds: ['u4'],
  },
  {
    id: 'c-dm-u5',
    type: 'dm',
    name: 'Management',
    subtitle: 'Management',
    memberIds: ['u5'],
  },
  {
    id: 'c-dept-pak',
    type: 'department',
    name: 'Pakistan Operations',
    emoji: '🇵🇰',
    subtitle: 'Pakistan Operations',
    memberIds: ['u1', 'u3', 'u4', 'u5'],
  },
  {
    id: 'c-dept-jpy',
    type: 'department',
    name: 'Japan Yard',
    emoji: '🇯🇵',
    subtitle: 'Japan Operations',
    memberIds: ['u1', 'u2', 'u5'],
  },
  {
    id: 'c-dept-acc',
    type: 'department',
    name: 'Accounts',
    emoji: '💰',
    subtitle: 'Accounts',
    memberIds: ['u1', 'u3', 'u5'],
  },
  {
    id: 'c-dept-shp',
    type: 'department',
    name: 'Shipping',
    emoji: '📦',
    subtitle: 'Shipping',
    memberIds: ['u1', 'u4', 'u5'],
  },
  {
    id: 'c-dept-sal',
    type: 'department',
    name: 'Sales',
    emoji: '📈',
    subtitle: 'Sales',
    memberIds: ['u3', 'u5'],
  },
  {
    id: 'c-dept-mgmt',
    type: 'management',
    name: 'Management',
    emoji: '👔',
    subtitle: 'Private Management Channel',
    restricted: true,
    memberIds: ['u1', 'u5'],
  },
  {
    id: 'c-veh-v1',
    type: 'vehicle',
    name: 'AT21235',
    subtitle: 'Toyota Hiace · Guyana',
    emoji: '🚗',
    recordId: 'v1',
    memberIds: ['u1', 'u2', 'u5'],
  },
  {
    id: 'c-veh-v2',
    type: 'vehicle',
    name: 'AT21236',
    subtitle: 'Toyota Prius · Jamaica',
    emoji: '🚗',
    recordId: 'v2',
    memberIds: ['u1', 'u2', 'u3'],
  },
  {
    id: 'c-veh-v3',
    type: 'vehicle',
    name: 'AT21237',
    subtitle: 'Toyota Aqua · Guyana',
    emoji: '🚗',
    recordId: 'v3',
    memberIds: ['u1', 'u2'],
  },
  {
    id: 'c-shp-s1',
    type: 'shipment',
    name: 'TYOGD5827400',
    subtitle: 'Guyana · SHIPPED',
    emoji: '🚢',
    recordId: 's1',
    memberIds: ['u1', 'u4', 'u2', 'u5'],
  },
  {
    id: 'c-shp-s2',
    type: 'shipment',
    name: 'TYOGD5827401',
    subtitle: 'Jamaica · BOOKING',
    emoji: '🚢',
    recordId: 's2',
    memberIds: ['u1', 'u4', 'u3'],
  },
];

const now = Date.now();
const t = (minsAgo: number) =>
  new Date(now - minsAgo * 60000).toISOString();

export const mockMessages: Message[] = [
  {
    id: 'm1',
    conversationId: 'c-dm-u2',
    senderId: 'u1',
    senderName: 'Raheel Hayat',
    message: 'Please check AT21235 vehicle condition.',
    timestamp: t(180),
    attachments: [],
    readStatus: 'read',
  },
  {
    id: 'm2',
    conversationId: 'c-dm-u2',
    senderId: 'u2',
    senderName: 'Japan Manager',
    message: 'Inspection completed. No major issue found.',
    timestamp: t(170),
    attachments: [],
    readStatus: 'read',
  },
  {
    id: 'm3',
    conversationId: 'c-dm-u2',
    senderId: 'u1',
    senderName: 'Raheel Hayat',
    message: 'Please upload the inspection photos.',
    timestamp: t(160),
    attachments: [],
    readStatus: 'read',
  },
  {
    id: 'm4',
    conversationId: 'c-dm-u2',
    senderId: 'u2',
    senderName: 'Japan Manager',
    message: 'Photos uploaded.',
    timestamp: t(155),
    attachments: [
      { id: 'a1', type: 'image', name: 'AT21235_front.jpg', size: '2.4 MB' },
      { id: 'a2', type: 'image', name: 'AT21235_rear.jpg', size: '2.1 MB' },
    ],
    readStatus: 'read',
  },
  {
    id: 'm5',
    conversationId: 'c-dept-jpy',
    senderId: 'u1',
    senderName: 'Raheel Hayat',
    message: 'Please confirm today\u2019s purchased vehicles.',
    timestamp: t(120),
    attachments: [],
    readStatus: 'read',
  },
  {
    id: 'm6',
    conversationId: 'c-dept-jpy',
    senderId: 'u2',
    senderName: 'Japan Manager',
    message: '3 vehicles purchased.',
    timestamp: t(110),
    attachments: [],
    readStatus: 'read',
  },
  {
    id: 'm7',
    conversationId: 'c-dept-jpy',
    senderId: 'u1',
    senderName: 'Raheel Hayat',
    message: 'Please update the ERP.',
    timestamp: t(100),
    attachments: [],
    readStatus: 'read',
  },
  {
    id: 'm8',
    conversationId: 'c-dept-jpy',
    senderId: 'u2',
    senderName: 'Japan Manager',
    message: 'Completed.',
    timestamp: t(95),
    attachments: [],
    readStatus: 'delivered',
  },
  {
    id: 'm9',
    conversationId: 'c-veh-v1',
    senderId: 'u1',
    senderName: 'Raheel Hayat',
    message: 'Please check the vehicle condition.',
    timestamp: t(90),
    attachments: [],
    readStatus: 'read',
  },
  {
    id: 'm10',
    conversationId: 'c-veh-v1',
    senderId: 'u2',
    senderName: 'Japan Yard',
    message: 'Inspection completed.',
    timestamp: t(80),
    attachments: [],
    readStatus: 'read',
  },
  {
    id: 'm11',
    conversationId: 'c-veh-v1',
    senderId: 'u2',
    senderName: 'Japan Yard',
    message: 'Front bumper has a minor mark.',
    timestamp: t(78),
    attachments: [],
    readStatus: 'read',
  },
  {
    id: 'm12',
    conversationId: 'c-veh-v1',
    senderId: 'u1',
    senderName: 'Raheel Hayat',
    message: 'Please upload photos.',
    timestamp: t(70),
    attachments: [],
    readStatus: 'read',
  },
  {
    id: 'm13',
    conversationId: 'c-veh-v1',
    senderId: 'u5',
    senderName: 'Management',
    message: 'Approved.',
    timestamp: t(60),
    attachments: [],
    readStatus: 'read',
  },
  {
    id: 'm14',
    conversationId: 'c-veh-v1',
    senderId: 'u2',
    senderName: 'Japan Manager',
    message: 'Inspection report attached.',
    timestamp: t(40),
    attachments: [
      { id: 'a3', type: 'pdf', name: 'AT21235_Inspection.pdf', size: '840 KB' },
    ],
    readStatus: 'delivered',
  },
  {
    id: 'm15',
    conversationId: 'c-shp-s1',
    senderId: 'u4',
    senderName: 'Shipping Team',
    message: 'Container loading completed.',
    timestamp: t(50),
    attachments: [],
    readStatus: 'read',
  },
  {
    id: 'm16',
    conversationId: 'c-shp-s1',
    senderId: 'u2',
    senderName: 'Japan Yard',
    message: 'All vehicles loaded.',
    timestamp: t(45),
    attachments: [],
    readStatus: 'read',
  },
  {
    id: 'm17',
    conversationId: 'c-shp-s1',
    senderId: 'u1',
    senderName: 'Operations',
    message: 'Documents received.',
    timestamp: t(30),
    attachments: [],
    readStatus: 'read',
  },
  {
    id: 'm18',
    conversationId: 'c-shp-s1',
    senderId: 'u5',
    senderName: 'Management',
    message: 'Approved.',
    timestamp: t(20),
    attachments: [],
    readStatus: 'read',
  },
  {
    id: 'm19',
    conversationId: 'c-dept-mgmt',
    senderId: 'u5',
    senderName: 'Management',
    message: 'Please review this week\u2019s shipment delays.',
    timestamp: t(200),
    attachments: [],
    readStatus: 'read',
  },
  {
    id: 'm20',
    conversationId: 'c-dept-mgmt',
    senderId: 'u1',
    senderName: 'Raheel Hayat',
    message: 'I will prepare the report.',
    timestamp: t(190),
    attachments: [],
    readStatus: 'read',
  },
  {
    id: 'm21',
    conversationId: 'c-dept-sal',
    senderId: 'u3',
    senderName: 'Sales Team',
    message: 'New inquiry for 5 units of Hiace from Guyana dealer.',
    timestamp: t(35),
    attachments: [],
    readStatus: 'delivered',
  },
  {
    id: 'm22',
    conversationId: 'c-dept-shp',
    senderId: 'u4',
    senderName: 'Shipping Team',
    message: 'Vessel departure confirmed for TYOGD5827400.',
    timestamp: t(15),
    attachments: [],
    readStatus: 'sent',
  },
];

export const mockTasks: Task[] = [
  {
    id: 't1',
    title: 'Check AT21235 inspection',
    description: 'Verify the inspection report and photos for vehicle AT21235.',
    assignedTo: 'Japan Yard',
    priority: 'HIGH',
    status: 'PENDING',
    relatedVehicleId: 'v1',
    createdAt: t(300),
    createdBy: 'Raheel Hayat',
  },
  {
    id: 't2',
    title: 'Confirm container loading',
    description: 'Confirm all vehicles are loaded into container TYOGD5827400.',
    assignedTo: 'Shipping',
    priority: 'NORMAL',
    status: 'COMPLETED',
    relatedShipmentId: 's1',
    createdAt: t(400),
    createdBy: 'Management',
  },
  {
    id: 't3',
    title: 'Upload AT21236 photos',
    description: 'Take and upload exterior photos of vehicle AT21236.',
    assignedTo: 'Japan Yard',
    priority: 'NORMAL',
    status: 'IN PROGRESS',
    relatedVehicleId: 'v2',
    createdAt: t(120),
    createdBy: 'Sales Team',
  },
  {
    id: 't4',
    title: 'Prepare shipment documents',
    description: 'Prepare Bill of Lading and export documents for TYOGD5827401.',
    assignedTo: 'Shipping',
    priority: 'HIGH',
    status: 'PENDING',
    relatedShipmentId: 's2',
    createdAt: t(60),
    createdBy: 'Management',
  },
  {
    id: 't5',
    title: 'Update ERP stock entries',
    description: 'Update the ERP with the latest 3 vehicles purchased today.',
    assignedTo: 'Operations',
    priority: 'LOW',
    status: 'PENDING',
    createdAt: t(240),
    createdBy: 'Japan Manager',
  },
];

export const mockNotifications: AppNotification[] = [
  {
    id: 'n1',
    type: 'mention',
    title: 'Japan Manager mentioned you',
    body: '“@Raheel please check AT21235.”',
    read: false,
    timestamp: t(50),
    link: '/chat?c=c-dm-u2',
  },
  {
    id: 'n2',
    type: 'message',
    title: 'New shipment message',
    body: 'Container TYOGD5827400 has been updated.',
    read: false,
    timestamp: t(30),
    link: '/chat?c=c-shp-s1',
  },
  {
    id: 'n3',
    type: 'task',
    title: 'Task assigned',
    body: 'You have been assigned: Check AT21235 inspection.',
    read: false,
    timestamp: t(20),
    link: '/tasks',
  },
  {
    id: 'n4',
    type: 'vehicle',
    title: 'Vehicle updated',
    body: 'AT21236 status changed to RESERVED.',
    read: true,
    timestamp: t(200),
    link: '/vehicles/v2',
  },
  {
    id: 'n5',
    type: 'shipment',
    title: 'Shipment updated',
    body: 'TYOGD5827400 departed on schedule.',
    read: true,
    timestamp: t(260),
    link: '/shipments/s1',
  },
];
